/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "bmp180.h"
#include "stm32f103xx.h"
#include "i2c.h"
#include "gpio.h"
#include "systemtick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

I2C_Handle_t i2c;


uint32_t rawTemperatureData = 0;
double temperatureData = 0;


int main(void)
{

	SystemTickInit(); // Initialize for using delay
	i2c.pI2Cx = I2C1;
	i2c.pI2CConfig.I2C_SCLSpeed = I2C_SCL_SPEED_SM; //I2C Standard mode
	i2c.pI2CConfig.I2C_FMDutyCycle = I2C_FM_DUTY_2;

	I2C_ClockControl(i2c.pI2Cx, ENABLE); // Enable i2c clock
	I2C_Init(&i2c); // initialze i2c from config

	bmp180GetCalibData(&i2c);

	while(1){
		rawTemperatureData = bmp180GetRawTemperature(&i2c);
		temperatureData = bmp180GetTemperature(&i2c);
	}
}
