/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "bmp180.h"
#include "stm32f103xx.h"
#include "i2c.h"
#include "gpio.h"
#include "systemtick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

I2C_Handle_t i2c;
BMP180_CALIBDATA calibData;
GPIO_Handle_t gpio;
uint32_t a = 0;
float b = 0;


int main(void)
{

	gpio.pGPIOX = GPIOA;
	gpio.GPIO_PinConfig.pinNumber = PIN_10;
	gpio.GPIO_PinConfig.pinMode = GPIO_MODE_PUSH_PULL_50MHZ;

	GPIO_ClockControl(gpio.pGPIOX, ENABLE);
	GPIO_Init(&gpio);
	SystemTickInit();
	i2c.pI2Cx = I2C1;
	i2c.pI2CConfig.I2C_SCLSpeed = I2C_SCL_SPEED_SM; //I2C Standard mode
	i2c.pI2CConfig.I2C_FMDutyCycle = I2C_FM_DUTY_2;

	I2C_ClockControl(i2c.pI2Cx, ENABLE); // Enable i2c clock
	I2C_Init(&i2c); // initialze i2c from config

	bmp180GetCalibData(&i2c, &calibData);

	while(1){
		a = bmp180GetRawTemperature(&i2c);
		b = bmp180GetTemperature(&i2c, &calibData);
//		a+=1;
//		delay_us(2000000);
	}
}
